# Example analysis
We'll be looking at a CSV dataset of people who tip at restaurants. The source data can be found in `data/tips.csv`.

The original dataset can be found at https://github.com/mwaskom/seaborn-data.

Tipping behavior at a popular US restaurant chain in a mall in 1990.

## Import pandas

In [3]:
import numpy as np
import pandas as pd
import seaborn as sb

## Import the dataset

In [4]:
df = pd.read_csv('data/tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  female     No  Sun  Dinner     4

## Describe the data

In [6]:
df.shape

(244, 7)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [9]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [10]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [14]:
np.round(df['tip'].mean() / df['total_bill'].mean() * 100, 2)

np.float64(15.15)

## Clean some data

In [30]:
df.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [31]:
df.sex = df.sex.str.title()
df.loc[df.sex.str.startswith("F"), "sex"] = "Female"
df.loc[df.sex.str.startswith("M"), "sex"] = "Male"

### Clean the smoker column

In [44]:
df.smoker.value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [43]:
df.smoker = df.smoker.str.title()
df.loc[df.smoker.str.startswith("N"), "smoker"] = "No"
df.loc[df.smoker.str.startswith("Y"), "smoker"] = "Yes"

In [45]:
df.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [46]:
df.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

## Add new columns

In [47]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [52]:
df['percent'] = df.tip / df.total_bill * 100
df.percent = df.percent.round(2)
df.head()

   total_bill   tip     sex smoker  day    time  size  percent
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94
1       10.34  1.66    Male     No  Sun  Dinner     3    16.05
2       21.01  3.50    Male     No  Sun  Dinner     3    16.66
3       23.68  3.31    Male     No  Sun  Dinner     2    13.98
4       24.59  3.61  Female     No  Sun  Dinner     4    14.68

In [57]:
df['bill_per_person'] = df.total_bill / df['size']
df.bill_per_person = df.bill_per_person.round(2)
df.head()

,total_bill,tip,sex,smoker,day,time,size,percent,bill_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,5.94,8.49
1,10.34,1.66,Male,No,Sun,Dinner,3,16.05,3.45
2,21.01,3.50,Male,No,Sun,Dinner,3,16.66,7.00
3,23.68,3.31,Male,No,Sun,Dinner,2,13.98,11.84
4,24.59,3.61,Female,No,Sun,Dinner,4,14.68,6.15

## Plot some data

## Get some statistsics